Repository macbre/sql-metadata, pull requests merged in 2021-05, with the labels that each got.

#135 tool.coverage.report: require 100% code coverage
  pyproject.toml
  sql_metadata/generalizator.py
Labels: internals

#136 CI - use Makefile commands
  .github/workflows/python-ci.yml
Labels: internals

#137 Introduce a compatibility layer for 1.x functions
  README.md
  sql_metadata/compat.py
  sql_metadata/parser.py
  test/test_compat.py
Labels: internals

#131 Column aliases support
  README.md
  sql_metadata/generalizator.py
  sql_metadata/keywords_lists.py
  sql_metadata/parser.py
  sql_metadata/token.py
  test/test_column_aliases.py
  test/test_getting_columns.py
  test/test_getting_tables.py
  test/test_mssql_server.py
  test/test_multiple_subqueries.py
  test/test_with_statements.py
Labels: enhancement

#126 Add a support for CREATE TABLE queries
  sql_metadata/parser.py
  test/test_create_table.py
Labels: enhancement

#140 Improved handling of tables names with leading digits
  sql_metadata/parser.py
  sql_metadata/token.py
  test/test_getting_columns.py
  test/test_getting_tables.py
  test/test_unions.py
Labels: enhancement

#146 Relevant keywords change, fix parenthesis helper
  README.md
  sql_metadata/__init__.py
  sql_metadata/keywords_lists.py
  sql_metadata/parser.py
  sql_metadata/token.py
  test/test_column_aliases.py
  test/test_comments.py
  test/test_compat.py
  test/test_create_table.py
  test/test_getting_columns.py
  test/test_getting_tables.py
  test/test_mssql_server.py
  test/test_multiple_subqueries.py
  test/test_normalization.py
  test/test_query.py
  test/test_redshift.py
  test/test_with_statements.py
Labels: bug

#148 CI - update poetry action version
  .github/workflows/python-ci.yml
Labels: internals
