Repository macbre/sql-metadata, pull requests merged in 2021-06, with the labels that each got.

#153 Update black to 21.5b2
  .github/workflows/black.yml
Labels: dependencies

#158 Automerge dependabot pull requests
  .github/workflows/auto-merge-dependabot.yml
Labels: internals

#159 Upload coverage report to Coveralls
  .github/workflows/python-ci.yml
  Makefile
  poetry.lock
  pyproject.toml
Labels: internals

#154 Resolving subqueries columns
  .github/workflows/python-ci.yml
  README.md
  sql_metadata/parser.py
  sql_metadata/token.py
  sql_metadata/utils.py
  test/test_column_aliases.py
  test/test_multiple_subqueries.py
Labels: enhancement

#157 Fix for create table with with clause
  sql_metadata/parser.py
  sql_metadata/token.py
  test/test_create_table.py
Labels: bug

#164 Handle leading comments in queries
  sql_metadata/parser.py
  test/test_getting_tables.py
  test/test_query_type.py
  test/test_values.py
Labels: bug

#162 Fix parsing with clauses, fix for #161
  sql_metadata/parser.py
  test/test_with_statements.py
Labels: bug

#170 Resolve columns coming from with queries
  README.md
  pyproject.toml
  sql_metadata/parser.py
  test/test_create_table.py
  test/test_mssql_server.py
  test/test_multiple_subqueries.py
  test/test_with_statements.py
Labels: enhancement

#171 Fix create schema
  sql_metadata/parser.py
  test/test_create_table.py
Labels: bug

#174 CI - install Poetry 1.1.7
  .github/workflows/python-ci.yml
Labels: internals
