Repository macbre/sql-metadata, pull requests merged in 2023-09, with the labels that each got.

#423 Handle cases tables preceded by complex queries
  sql_metadata/parser.py
  test/test_getting_tables.py
Labels: enhancement

#403 Update keywords_lists.py to add Natural Join
  sql_metadata/keywords_lists.py
Labels: enhancement, SQLite

#429 Add a test coverage for the NATURAL JOIN
  test/test_sqlite.py
Labels: SQLite
